# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/notebooks',
                'doc_host': 'https://kzvezdarov.github.io',
                'git_url': 'https://github.com/kzvezdarov/notebooks',
                'lib_path': 'notebooks'},
  'syms': {'notebooks.core': {'notebooks.core.foo': ('core.html#foo', 'notebooks/core.py')}}}
